### ISSUE TITLE
Aero & Performance comparison

### ISSUE THREAD

**Issue by maplerichie** [aerogo/aero#11]
Is Aero aim as full stack web framework?

For performance, can it compete with Beego and Iris-go?

**Comment by akyoto** [comment]
Hi there @maplerichie :wave:,

I'll try to answer both of your questions but this post will focus on your first question only: Is Aero a full stack web framework?

[The answer is a definite no](https://eduardurbach.com/post/separation-of-concerns).

I try to build my packages with as little features as possible, which means each package tries to only do the minimum it needs to do. The [aero](https://github.com/aerogo/aero) package is a web server and does only things related to serving content to the browser.

If you're asking whether the [collection of web libraries](https://github.com/aerogo) can make a full-stack web framework then the answer would be: Yes, it can.

I am using [pixy](https://github.com/aerogo/pixy) & [scarlet](https://github.com/aerogo/scarlet) for frontend things by bundling them up via [pack](https://github.com/aerogo/pack). On the backend, I use [nano](https://github.com/aerogo/nano) as a high-performance in-memory database for everything that's not "big data" and fits into memory. [run](https://github.com/aerogo/run) is my development watcher which restarts the project on changes.

Is the combination of all of these packages a full-stack framework? Yes, you could call it that if you want to work with these libraries. You are by no means forced to use my template & styling engine, you can swap them out for something else if you wish to do so.

Is the main package aero a full-stack framework? Definitely not: It focuses on one thing, which is serving content, and tries to do that one thing very well.

Sorry for the delay on the reply but I hope this explanation answered your first question.

**Comment by akyoto** [comment]
Closing, I will post performance comparisons once I get a working beego example.

**Comment by akyoto** [comment]
[Benchmarks](https://github.com/aerogo/aero/blob/master/docs/Benchmarks.md) are available now if you'd like to compare the performance to other routers.
