### ISSUE TITLE
Is it possible to increase maxParams to some bigger value?

### ISSUE THREAD

**Issue by PratikDeoghare** [aerogo/aero#19]
https://github.com/aerogo/aero/blob/09572e31baa5840a498aacfcf6fe5fd17f5e5ac6/Context.go#L34

`BenchmarkAero_Param20` in the benchmarks [1] panics because of the limit on `maxParams`. 

Would it be acceptable to set `maxParams` to some bigger value (32?) or make it configurable? 

[1] https://github.com/julienschmidt/go-http-routing-benchmark/pull/93

**Comment by akyoto** [comment]
Having over 16 parameters in your route is most likely the result of bad design.
If someone can convince me why one would need 17+ parameters in a single route, please do so.

I understand that it's for the purpose of the benchmark, but real-world use cases are more important.

**Comment by PratikDeoghare** [comment]
> I understand that it's for the purpose of the benchmark, but real-world use cases are more important.

I agree.
