### ISSUE TITLE
static path match error

### ISSUE THREAD

**Issue by kiyonlin** [aerogo/aero#20]
Hi, I'm wondering if the static path match ([tree.go#L29-L37](https://github.com/aerogo/aero/blob/master/tree.go#L29-L37) and [tree.go#L121-L128](https://github.com/aerogo/aero/blob/master/tree.go#L121-L128)) is wrong?

Here is the code snippet:
```go
package main

import "github.com/aerogo/aero"

func main() {
	app := aero.New()
	app.Get("/:a/b/c", func(c aero.Context) error {
		return c.String("param a")
	})
	app.Get("/a/b/c", func(c aero.Context) error {
		return c.String("const a")
	})
	app.Run()
}
```

And request result:
```bash
http :4000/a/b/c
HTTP/1.1 200 OK
Content-Length: 7
Content-Type: text/plain; charset=utf-8
Date: Fri, 14 Aug 2020 11:24:04 GMT

const a
```

**Comment by akyoto** [comment]
Late reply, but that's actually a feature, see [Explanation](https://github.com/aerogo/aero/blob/master/docs/Benchmarks.md#explanation).
The order of statements is irrelevant to the router and static paths have the highest priority.
