### ISSUE TITLE
HTTP methods supported?

### ISSUE THREAD

**Issue by peterljung** [aerogo/aero#8]
Are only `GET` and `POST` methods supported by this framework?

I have used [gorilla/mux](https://github.com/gorilla/mux) for routing before and I end up with code like this:

    r.HandleFunc("/api/accounts", AddAccount).Methods("POST")
    r.HandleFunc("/api/accounts", GetAccounts).Methods("GET")
    r.HandleFunc("/api/accounts/{key}", UpdateAccount).Methods("POST")
    r.HandleFunc("/api/accounts/{key}", DeleteAccount).Methods("DELETE")

At least `DELETE` seems very useful in any REST like api.

**Comment by akyoto** [comment]
I have added the `app.Delete` routing method in 1.2.6.

Could you try to update your version with `go get -u github.com/aerogo/aero`?

**Comment by peterljung** [comment]
Thanks!
